### ISSUE TITLE
Export 2D data as cell

### ISSUE THREAD

**Issue by emielverstegen** [nens/threedigrid#102]
For visualization purposes it would be handy if 2D nodes could be exported as polygons (the actual 2D cell instead of the cell-center point).
Use case: Visualizing the spatial infiltration rate of a timestep (or an aggregation of timesteps).

**Comment by RichardB9** [comment]
The GeoJsonSerializer visualises the 2D cells as polygons. You can use the GeoJsonSerializer with the GridAdminH5Export and set the export_method to 'to_geojson'. See example below

```python
from threedigrid.admin.prepare import GridAdminH5Export

exporter = GridAdminH5Export(
    gridadmin_file,
    export_method='to_geojson',
    target_epsg_code='4326',
    destination=tempdir,  # Your destination folder
    indent=None
)
exporter.export_grid()
```

This will export both openwater and groundwater cells.
