### ISSUE TITLE
Possible breach depth problems.

### ISSUE THREAD

**Issue by jpprins1** [nens/threedigrid#115]
From Emiel: (not tried to reproduced yet)

depth = breach.timeseries(start_time=1,end_time=gr.nodes.timestamps[-1]).breach_depth
vervangen door:
depth = breach.timeseries(start_time=1,end_time=gr.nodes.timestamps[-1]).get_field_value('breach_depth')

**Comment by Jonasvsl** [comment]
@jpprins1 is this still open?

**Comment by jpprins1** [comment]
Issue is fixed by using the new breaches object under lines like:
ga.lines.breaches.timeseries(start_time=1, end_time=ga.nodes.timestamps[-1]).breach_depth

(ga being a GridH5ResultAdmin instance)
