### ISSUE TITLE
extracting waterlevel timeseries does not work

### ISSUE THREAD

**Issue by valdemetriades** [nens/threedigrid#118]
#subset only 1D nodes
nodes_1d = gr.nodes.subset('1D_ALL')

#Get the x,y-coordinates from the 1D nodes
nodes_1d_coordinates = nodes_1d.coordinates

#Read the whole timeserie for the waterlevel for the subset of 1D nodes into the wl variable
wl = nodes_1d.timeseries(start_time=0,end_time=gr.nodes.timestamps[-1]).s1

--> error: TypeError: Indexing arrays must have integer dtypes

**Comment by jpprins1** [comment]
Fixed in most recent version (tested under Python 3.7)
