### ISSUE TITLE
threedigrid breaks with previous versions

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedigrid#119]
The usage of these files used to be likes this:

#now with new results:
base_path =r"C:\temp\schermer\sim_12980_Schermer_test_Emiel_op_prod"
grid_file = base_path + os.sep + "gridadmin.h5"
result_file = base_path + os.sep + "results_3di.nc"
gr = GridH5ResultAdmin(grid_file, result_file)
ga = GridH5Admin(grid_file)

However, with the current prod version it results in this:
(
3Di simulation API (latest version: 3.0)
Framework release: 1.0.29
3Di core release: 2.0.13
deployed on: 10:17AM (UTC) on December 09, 2020
)

Also the same result I get on curren staging environment:
3Di simulation API (latest version: 3.0)
Framework release: 1.0.41
3Di core release: 2.0.15
deployed on: 08:30AM (UTC) on February 22, 2021

`---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-7-52f5a266f4fc> in <module>
      3 grid_file = base_path + os.sep + "gridadmin.h5"
      4 result_file = base_path + os.sep + "results_3di.nc"
----> 5 gr = GridH5ResultAdmin(grid_file, result_file)
      6 ga = GridH5Admin(grid_file)

~\AppData\Local\Continuum\anaconda3\envs\threedi\lib\site-packages\threedigrid\admin\gridresultadmin.py in __init__(self, h5_file_path, netcdf_file_path, file_modus)
     49         self.netcdf_file = h5py.File(netcdf_file_path, file_modus)
     50         self.set_timeseries_chunk_size(DEFAULT_CHUNK_TIMESERIES.stop)
---> 51         self.version_check()
     52 
     53     def set_timeseries_chunk_size(self, new_chunk_size):

~\AppData\Local\Continuum\anaconda3\envs\threedi\lib\site-packages\threedigrid\admin\gridresultadmin.py in version_check(self)
    114         """
    115 
--> 116         if self.threedicore_result_version != self.threedicore_version:
    117             logger.warning(
    118                 '[!] threedicore version differ! \n'

~\AppData\Local\Continuum\anaconda3\envs\threedi\lib\site-packages\threedigrid\admin\gridresultadmin.py in threedicore_result_version(self)
    172         """
    173         try:
--> 174             return self.netcdf_file.attrs.get('threedicore_version')
    175         except AttributeError:
    176             logger.error(

~\AppData\Local\Continuum\anaconda3\envs\threedi\lib\_collections_abc.py in get(self, key, default)
    658         'D.get(k[,d]) -> D[k] if k in D, else d.  d defaults to None.'
    659         try:
--> 660             return self[key]
    661         except KeyError:
    662             return default

h5py\_objects.pyx in h5py._objects.with_phil.wrapper()

h5py\_objects.pyx in h5py._objects.with_phil.wrapper()

~\AppData\Local\Continuum\anaconda3\envs\threedi\lib\site-packages\h5py\_hl\attrs.py in __getitem__(self, name)
     79 
     80         arr = numpy.ndarray(shape, dtype=dtype, order='C')
---> 81         attr.read(arr, mtype=htype)
     82 
     83         if len(arr.shape) == 0:

h5py\_objects.pyx in h5py._objects.with_phil.wrapper()

h5py\_objects.pyx in h5py._objects.with_phil.wrapper()

h5py\h5a.pyx in h5py.h5a.AttrID.read()

h5py\_proxy.pyx in h5py._proxy.attr_rw()

OSError: Unable to read attribute (no appropriate function for conversion path)`

**Comment by Jonasvsl** [comment]
@jpprins1 is this solved by pinning to 2.10 or is more required from our side?

**Comment by jpprins1** [comment]
Looks indeed like the 2.10 problem. We moved to 3.x in the newest threedigrid release.
