### ISSUE TITLE
Migrate large objects to git lfs

### ISSUE THREAD

**Issue by caspervdw** [nens/threedigrid#124]
Git is not meant for checking in large binary files. The issue is that they never get deleted, as soon as you update a 100MB file, your repo will increase with 100MB. Currently this repo is already pretty large mainly due to checked-in netcdfs and hdf5 files:

```
$ git lfs migrate info --everything
migrate: Sorting commits: ..., done.                                                                                                   
migrate: Examining commits: 100% (380/380), done.                                                                                      
*.nc            257 MB    12/12 files(s)        100%
*.h5            122 MB      9/9 files(s)        100%
*.sqlite        6.3 MB      1/1 files(s)        100%
*.py            4.2 MB  743/745 files(s)        100%
*.bck           3.5 MB      2/2 files(s)        100%
```

I have been using Git LFS to solve this issue for some time, it works seamlessly. But migrating to git lfs involves rewriting the git history (replacing binary blobs with pointers). What do you think? @larsclaussen @jpprins1 

See: https://git-lfs.github.com/

**Comment by jpprins1** [comment]
Good point, didn't really thought about this when adding the test files. Although they should not change very often, it's a good improvement to use Git LFS instead. 

How much time does it take (approx) to fix/change this?

**Comment by caspervdw** [comment]
I never migrated the complete history, but I guess I will figure it out in half an hour or so
.

**Comment by caspervdw** [comment]
So to be clear on this: I'll migrate the large files to git LFS, rewriting the complete history of this repo. This means all local clones will need some force checkout to get in sync again.
