### ISSUE TITLE
importerror threedigrid

### ISSUE THREAD

**Issue by rebeccavw** [nens/threedigrid#134]
![image](https://user-images.githubusercontent.com/36692319/127838126-8f697f8d-4440-4151-874d-4c73f7e121d5.png)

Samen met @valdemetriades gekeken naar een jupyter notebook die gebruik maakt van threedigrid.
Probleem: installeren van package threedigrid gelukt, maar alsnog een fail in Jupyter notebook: "ImportError: DLL load failed while importing defs: The specified procedure could not be found." Zowel met conda als met pip importeren, leidt tot dezelfde import error.

Wat is de workaround/oplossing hiervoor?

**Comment by jpprins1** [comment]
Waarschijnlijk een missende of verkeerde hdf5 library.

**Comment by rebeccavw** [comment]
Dank voor de tip Jelle, het is opgelost door de hdf5 library te installeren
