### ISSUE TITLE
[Bug]: filtering on active breaches does not work: filter(kcu__eq=56)

### ISSUE THREAD

**Issue by Overmeen** [nens/threedigrid#142]
### Contact Details

stijn.overmeen@nelen-schuurmans.nl

### What happened?

Issue with the API

`active_breaches=gr.lines.breaches.filter(kcu__eq=56)` gives empty array, while there is an active breach.
Also for `gr.breaches.filter(kcu__eq=56)`.

`kcu__eq=55` does work, so with a mask (based on breach width), I was able to track the active breach id:

```
mijn_breaches=gr.lines.breaches.filter(kcu__eq=55).data
masks=gr.lines.breaches.filter(kcu__eq=55).breach_width[1,:] > 0
element=0
for mask in masks:
    if mask:
        breach_id=mijn_breaches.get('content_pk')[element]
    element=element+1
```

However, it should work with 56 as the documentation states: _https://threedigrid.readthedocs.io/en/latest/miscellaneous.html?highlight=kcu#line-types_

### Version

1.0.2 (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caspervdw** [comment]
An active breach does not exist in the gridadmin. In the gridadmin all breaches are 55 (potential). Only internally in the calccore, breaches may be set to active.
