### ISSUE TITLE
Exchange level in gridadmin geopackage is wrong sometimes

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedigrid#168]
The `exchange_level` of the `obstacle` layer in the geopackage export of the gridadmin should have the same value as the `crest_level` of the obstacle (or levee) in the schematisation sqlite (unless the crest level is entirely below the DEM, but that is not the case here).

The image below shows a case where this goes wrong somehow:
![image](https://user-images.githubusercontent.com/26224299/194034293-7aa7ec5f-a611-47bc-9909-3f5c904c744b.png)

How to reproduce:
- download this gridadmin.h5 file: [gridadmin.zip](https://github.com/nens/threedigrid/files/9715272/gridadmin.zip)
- export to geopackage, you will get this result: [Hekerbeek na maatregelen Landelijk T100.zip](https://github.com/nens/threedigrid/files/9715280/Hekerbeek.na.maatregelen.Landelijk.T100.zip)
- obstacle with line_id 2510 has a exchange_level of 69.11
- for reference, see obstacle with id 283 in this sqlite (crest_level = 119.5): 
[Hekerbeek na maatregelen Landelijk T100 SQLITE.zip](https://github.com/nens/threedigrid/files/9715295/Hekerbeek.na.maatregelen.Landelijk.T100.SQLITE.zip)
- Rasters: [rasters.zip](https://github.com/nens/threedigrid/files/9753021/rasters.zip)

**Comment by jpprins1** [comment]
@martijn-siemerink is the information incorrect or do we need to use a different value? (flod/flou seems to be this value).

```
In [3]: ga.lines.filter(id=2510).data
Out[3]: 
OrderedDict([('ds1d_half', array([16.])),
             ('id', array([2510], dtype=int32)),
             ('kcu', array([101], dtype=int32)),
             ('content_pk', array([-9999], dtype=int32)),
             ('flod', array([119.5])),
             ('flou', array([119.5])),
             ('line',
              array([[2051],
                     [2091]], dtype=int32)),
             ('invert_level_end_point', array([nan])),
             ('line_coords',
              array([[189038.5],
                     [320882. ],
                     [189070.5],
                     [320882. ]])),
             ('cross1', array([-9999], dtype=int32)),
             ('ds1d', array([32.])),
             ('dpumax', array([69.11000061])),
             ('zoom_category', array([-9999], dtype=int32)),
             ('cross2', array([-9999], dtype=int32)),
             ('cross_pix_coords',
              array([[6592],
                     [4416],
                     [6592],
                     [4480]], dtype=int32)),
             ('line_geometries',
              array([array([189038.5, 189070.5, 320882. , 320882. ])], dtype=object)),
             ('content_type', array([b''], dtype='|S10')),
             ('cross_weight', array([nan])),
             ('lik', array([4], dtype=int32)),
             ('invert_level_start_point', array([nan]))])
```

**Comment by leendertvanwolfswinkel** [comment]
Problem also occurs for flowlines, e.g. in flowline 24044 in the Hekerbeek model: 
![image](https://user-images.githubusercontent.com/26224299/194951719-0f0780f9-7d6f-45c3-972d-37782633bae4.png)

**Comment by caspervdw** [comment]
1D-2D lines will get the exchange level of crossed levees or obstacles so that part of this ticket is solved.
