### ISSUE TITLE
Export to Geopackage: Node layer field 'bottom_level' and 'drain_level' are missing

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedigrid#178]
... and connection_node_storage_area is named 'connection_node_storage_are' (last character is missing)

- [x] Add float field 'bottom_level' ('dmax' in gridadmin)
- [x] Add float field 'drain_level' ('drain_level' in gridadmin)
- [x] Rename 'connection_node_storage_are' to 'connection_node_storage_area'

CC @benvanbasten-ns @arjanverkerk

**Comment by leendertvanwolfswinkel** [comment]
@benvanbasten-ns @arjanverkerk I don't think we need to put any effort in comptability with older computational grid geopackages that do not contain these fields

**Comment by benvanbasten-ns** [comment]
@jpprins1 please let us know when a new version of threedigrid is available, alstublieft, dankjewel

**Comment by jpprins1** [comment]
Casper was me al voor: https://pypi.org/project/threedigrid/
