### ISSUE TITLE
NODATA value in HDF5 file is wrong/missing TOPDESK 2401 0070

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedigrid#214]
Gemeld door Thomas, @daanvaningen ik meen me te herinneren dat jij laatst bij de heads-up ook iets dergelijks meldde?

**Comment by daanvaningen** [comment]
Eli gaf aan dat dit niet goed staat in de netcdf. Ik heb toen ff snel gekeken in de calccore of ik het kon vinden maar kwam daar niks tegen

**Comment by daanvaningen** [comment]
looks like we didn't set it correctly in the calccore. Maybe we did previously but we have switched the way in which we create and fill netcdf files. Made a fix
