### ISSUE TITLE
Include exchange level in breaches GeoJSON

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedigrid#219]
There is a field `levl`, but the value for this field is not the exchange level. Perhaps that is just it?

**Comment by leendertvanwolfswinkel** [comment]
https://github.com/nens/nens-frontends/issues/1673

**Comment by daanvaningen** [comment]
`levl` is the line which can be used to extract the exhange level from. In the geojson export I implemented that we make this mapping and so `levl` will contain the actual exchange level in the geojson export.

**Comment by leendertvanwolfswinkel** [comment]
@daanvaningen I tested it as follows:
- Uploaded a new revision for a schematisation with breaches,  https://management.staging.3di.live/schematisations/566/6049?organisation=b08433fa47c1401eb9cbd4156034c679
- Downloaded the breaches.json via https://api.staging.3di.live/v3/threedimodels/16663/geojson/breaches/download/

It looks like the `levl` is still the ID, not the exchange level:

```
{
         "type":"Feature",
         "geometry":{
            "type":"LineString",
            "coordinates":[
               [
                  5.748287,
                  50.961255
               ],
               [
                  5.748834,
                  50.962832
               ]
            ]
         },
         "properties":{
            "id":1,
            "code":"new",
            "display_name":"meers_bovenstrooms",
            "content_pk":1,
            "levmat":1,
            "levbr":3.8,
            "kcu":null,
            "levl":12506,
            "coordinates":[
               5.748748612453184,
               50.962584956171234
            ],
            "model_type":"Breaches"
         }
      }
```
