### ISSUE TITLE
threedigrid: remove sphinx_rtd_theme dependency

### ISSUE THREAD

**Issue by benvanbasten-ns** [nens/threedigrid#221]
Recently a dependency of sphinx_rtd_theme has been added:

```
lightweight_requirements = [
    "numpy>=1.15",
    "h5py>=2.9",
    "six",
    "sphinx_rtd_theme>=0.4.3",
]
```

When using ``threedigrid`` in Lizard, this causes many additional dependencies to be required.

Remove ``sphinx_rtd_theme``  from the code dependencies, but keep it in the docker/env so the doc can be generated.

**Comment by daanvaningen** [comment]
api is still on 2.2.3
